version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: rails-app
    environment:
      RAILS_ENV: development
      DATABASE_HOST: db
      REDIS_HOST: redis
      WWWUSER: "${WWWUSER:-1000}"
      WWWGROUP: "${WWWGROUP:-1000}"
    ports:
      - "${APP_PORT:-3000}:3000"
    volumes:
      - ".:/myapp"
    networks:
      - spoor-network
    depends_on:
      - db
      - redis

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: rails
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rails_development
    ports:
      - "${FORWARD_DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - spoor-network

  redis:
    image: redis:latest
    ports:
      - "${FORWARD_REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    networks:
      - spoor-network

networks:
  spoor-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
